### ISSUE TITLE
please always tag a new release when fixing bugs or doing changes

### ISSUE THREAD

**Issue by TayouVR** [rrazgriz/RATS#24]
in 1.1.2 there was a bug and you just pushed something right after in another commit without bumping version and tagging. The last git tag sits on the commit before the fix still, which breaks things like [OpenUPM packaging](https://openupm.com/packages/one.razgriz.rats/)
I understand, that the primary distribution of RATS goes through the VCC, or as download from releases, but I would really like OpenUPM to have the latest changes too, currently i have to stay on 1.1.1 in order to avoid the script compilation errors.
![image](https://github.com/rrazgriz/RATS/assets/31988415/b70b53c9-5ae4-4c64-b799-b8ea0cffeec6)

---

PS:
in the long term, it would also be cool if RATS had [com.needle.editorpatching](https://openupm.com/packages/com.needle.editorpatching/) as dependency, so that installing harmony through (Open)UPM is automatic. I have no idea if that would interfere with the VCC though, probably not, but i can't expect you to add a dependency for this niche usecase.

**Comment by rrazgriz** [comment]
This was a bit confusing, I had to do some digging to understand how OpenUPM works. The 1.1.2 tag is on the correct commit in this GitHub repo. From my understanding OpenUPM only builds a release for a version once, when it sees a tag for the first time - so the tag is associated with the wrong commit. Unfortunately, I can't take responsibility for the behavior of an external service when it's not in my purview.

In this repo, releases are ground truth for (relatively) stable versions, and tags are secondary to that - used to indicate a release. I target VCC and Standalone package builds using GitHub actions, so I can't guarantee compatibility with OpenUPM's package build system.

It's a bit strange to be presented with a service that builds independently on top of this software, and then be expected to support its as an additional release channel, with additional requirements and considerations. Given this, I'm going to mark this issue as `wontfix`, but I'll try to be mindful of this behavior when adding tags to commits in this repo. Please note that this does not mean I'm guaranteeing OpenUPM compatibility.

`com.needle.editorpatching` is a cool package, but I won't be adding an OpenUPM dependency. Harmony distribution is already complex enough with other packages including the plugin piecemeal.

**Comment by TayouVR** [comment]
> It's a bit strange to be presented with a service that builds independently on top of this software, and then be expected to support its as an additional release channel, with additional requirements and considerations. Given this, I'm going to mark this issue as `wontfix`, but I'll try to be mindful of this behavior when adding tags to commits in this repo. Please note that this does not mean I'm guaranteeing OpenUPM compatibility.

I did note that I'm aware you don't officially distribute to OpenUPM, I was just hoping you could tag another release and bump the version so the bugfix after the 1.1.2 tag can be available there.

I also understand you don't want to add the dependency, I didn't expect you too, just wanted to throw it in the room.


> but I'll try to be mindful of this behavior when adding tags to commits in this repo.

thank you! 

VRCFury currently uses a action to automatically bump version number and add a tag. Maybe something like that could help to make releases and versioning more stable and automated. But at that point, thats another whole can of worms x3

**Comment by rrazgriz** [comment]
I've published a new release (1.1.3) that appears to have triggered a OpenUPM build successfully.
